apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.exporter.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "aspnet-db.labels" . | nindent 4 }}
spec:
  type: {{ .Values.exporter.service.type }}
  ports:
   - port: {{ .Values.exporter.service.port }}
     targetPort: {{ .Values.exporter.service.targetPort }}
  selector:
      {{- include "aspnet-db.selectorLabels" . | nindent 6 }}