{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: db-connection
  namespace: {{ .Values.namespace }}
  labels:
    app: aspnetapp-db-connection
    {{- include "aspnet-auth-db.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
data:
  dbHost: cG9zdGdyZXM=
  dbPort: NTQzNw==
  dbName: b3R1c0F1dGhEYg==
  dbUsername: RGJVc2Vy
  dbPassword: aFhPQUAlai1NJkdZMWNx
{{- end }}