{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: db-connection
  namespace: {{ .Values.namespace }}
  labels:
    app: aspnetapp-db-connection
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: aspnet-app
    meta.helm.sh/release-namespace: otus1
  namespace: otus
data:
  dbHost: cG9zdGdyZXM=
  dbPort: NTQzNw==
  dbName: bXlhcHA=
  dbUsername: bXl1c2Vy
  dbPassword: cGFzc3dk
{{- end }}