{{- if .Values.unauthIngress.enabled -}}
{{- $svcPort := .Values.service.port -}}
{{- $svcName := .Values.service.name -}}
{{- if and .Values.unauthIngress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.unauthIngress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.unauthIngress.annotations "kubernetes.io/ingress.class" .Values.unauthIngress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: aspnetcore-user-unauth-ingress
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "aspnet-auth-user-chart.labels" . | nindent 4 }}
  {{- with .Values.unauthIngress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    {{- range .Values.unauthIngress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
        - path: {{ .path }}
          {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
          pathType: {{ .pathType }}
          {{- end }}
          backend:
            {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
            service:
              name: {{ $svcName }}
              port:
                number: {{ $svcPort }}
            {{- else }}
            serviceName: {{ $svcName }}
            servicePort: {{ $svcPort }}
            {{- end }}
        {{- end }}
    {{- end }}
{{- end }}
