apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.jsonConfigName}}
  namespace: {{ .Values.namespace }}
  labels:
    app: aspnetapp-auth-config
    {{- include "aspnet-auth-user-chart.labels" . | nindent 4 }}
data:
  config.json: ewogICJDb25uZWN0aW9uSW5mbyI6IHsKICAgICJEYkhvc3QiOiAicG9zdGdyZXMiLAogICAgIkRiUG9ydCI6IDU0MzcsCiAgICAiRGJOYW1lIjogIm90dXNBdXRoRGIiCiAgfSwKICAiVG9rZW5PcHRpb25zIjogewogICAgIlB1YmxpY0tleSI6ICJNSUdKQW9HQkFJMk5BMm9OeDN1cVVRbHk3aFlCTnFLaUt0Y3hqTmkxRkwyaHQ4Y2Y2eGgyVlM0dDRwNFVHaXl4Wi9lYVRocWlNdWdRZUhFaFJUNVZsVFVZMWZDOStRSWhaTUFrUmc4YXVlN3VDeVRlRG9kMkltQUdWUktDdW9BdGhvckU4RlZ5bXdxUktvWENCL3ZqcVBuSlVGOHozVTd6Wm05amhlTExTTnVMTTNXaUV0NVRBZ01CQUFFPSIsCiAgICAiSXNzdWVyIjogIkFzcE5ldENvcmUuQXV0aFNlcnZpY2UiCiAgfQp9