# Default values for aspnet-db.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: otus

replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

exporter:
  replicaCount: 1
  port: 9187
  image:
    repository: wrouesnel/postgres_exporter
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"
  service:
    type: NodePort
    port: 9187
    targetPort: 9187
    name: "exporter"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 5437
  targetPort: 5432
  name: "postgres"
  
secrets:
  create: true
  
migration:
  execute: true
  
metrics:
  serviceMonitor:
    enabled: true
