# Default values for aspnet-db.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: {{ default "otus-pushkarev-auth" .Release.Namespace }}

replicaCount: 1

service:
  type: NodePort
  port: 5437
  targetPort: 5432
  name: "postgres"
  
secrets:
  create: true  
